version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn todoproject.wsgi:application -c gunicorn.conf.py"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=todoproject_dev
      - POSTGRES_USER=todouser_dev
      - POSTGRES_PASSWORD=todopass_dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume: